# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xresponse
Summary:    Tool for synthethizing user X input events
Version:    1.2.1
Release:    mer1
Group:      Development/Tools/Other
License:    GPL v2
URL:        git://gitorious.org/maemo-tools/xresponse.git
Source0:    xresponse-%{version}.tar.gz
Source100:  xresponse.yaml
Requires:   libXdamage
Requires:   libXi
Requires:   libXtst
Requires:   libXext
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(xtst)
BuildRequires:  pkgconfig(xdamage)
BuildRequires:  pkgconfig(xi)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(x11)


%description
Tool for synthethizing user X input events and for reporting X input
and window update events and their timestamps. Either whole X screen
and/or individual windows can be tracked.




%prep
%setup -q -n src

# >> setup
./autogen.sh
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_bindir}/xresponse
%{_mandir}/man1/xresponse.1.gz
# << files


